#Goal: Get the number of rows and columns from the user. Create a 2D array with increasing numbers according to these dimensions. Filter out the odd and even numbers.

In [16]:
import random 
import numpy as np

In [38]:
row=int(input("Enter the number of row"))
column=int(input("Enter the number of column"))

Enter the number of row 5
Enter the number of column 3


In [90]:
random_numbers_count=row*column
numbers=np.arange(random_numbers_count)
# arange() is preferred over randint() here to maintain sequential order randint would generate random integers, which breaks the consistent structure we need.
# arange() is preferred over linspace() here to ensure integer outputs linspace generates evenly spaced values, but returns floats by default, which may not fit integer-based logic.

In [64]:
array_2D=numbers.reshape((5,3)) #Since reshpe does not affect the original array, it is assigned to the variable

In [106]:
print(array_2D[array_2D % 3 == 0])
# This line filters the array_2D and prints only the elements that are divisible by 3.
# It uses boolean indexing: array_2D % 3 == 0 creates a mask of True/False values


[ 0  3  6  9 12]


In [108]:
print(array_2D[array_2D % 2 == 0])

[ 0  2  4  6  8 10 12 14]


In [118]:
print(array_2D[(array_2D % 2 == 0 ) & (array_2D % 3==0)])
# We use '&' instead of 'and' because we are performing element-wise logical operations on arrays.

[ 0  6 12]
